# edited to work with Ansible Tower
---
- hosts: all
  connection: local
  gather_facts: false 
  tasks:
  - name: Get all Device Health
    cisco.dnac.device_health_info:
      dnac_host: "{{ansible_host}}"
      dnac_username: "{{dnac_username}}"
      dnac_password: "{{dnac_password}}"
      dnac_verify: "{{dnac_verify}}"
      #deviceRole: string
      #siteId: string
      #health: string
      #startTime: 0
      #endTime: 0
      #limit: 0
      #offset: 0
    register: device_health
  - name: Display device health 
    debug: 
      var: device_health
